### PR TITLE
Migrated from Cairo to CanvasKit

### PR DESCRIPTION
**Pull request by khovansky-al**
Tried to make all changes as consistent as possible with how it was previously written, only changing what was related to the underlying canvas library. Had to fix a couple of linter issues as well. So although I have lots of suggestions to code architecture, I didn't implement them.

We previously discussed that we should incorporate canvaskit as a git submodule into our repository but that is not really feasible. CanvasKit is basically Skia subset, which is a huge library itself. To build it with WASM target you have to install Emscripten compiler (that is a huge download) and a bunch of third-party dependencies, as well as Google's building toolkit. It can be automated into a script but it won't work on CI obviously and I feel like rebuilding the whole library is a REALLY rare case. We can live with pre-built library in git until they release an npm module that can be dropped into dependencies, I think.

I updated the sanity test with new generated output that was verified in browser as well as the travis configuration to make tests green. Had to bump Node version to 8 since we are using WASM now. Also due to that I had to update eslint version and make changes to eslint config to support new syntax.

Made slight changes to README to remove Cairo references, of course.

### CODE REVIEW

**Comment by jonathantneal** [comment]
You are welcome to make more changes or completely refactor the plugin. This is an old one that was too long neglected.

**Comment by khovansky-al** [comment]
Great, thank you. Are we going to publish updated package on npm?

**Comment by ai** [comment]
@khovansky-al can I ask you to write a tweet about it in English?

You need to say that conic-gradient polyfill is now pure JS and easy to use (since it doesn’t use Cairo anymore). Then you need to show some examples of this plugin. And you need to mention `@leaverou` and `@postcss`.

I will gave you a marketing support with all my sources.

If you need help with English, feel free to post templates here.

**Comment by ai** [comment]
I put your name in Cult of Martians task https://cultofmartians.com/tasks/postcss-conic.html

Great work :+1:

**Comment by jonathantneal** [comment]
@khovansky-al, yes, it can’t be under-estimated what you have done. I would like to make you a co-maintainer of this project. I will make some time to cleanup any areas of the project I had left messy.

**Comment by khovansky-al** [comment]
@jonathantneal @ai Thank you, I am incredibly excited :)
Have been working on the examples today (basically trying to compile the ones from @LeaVerou polyfill page) and realized that a little more changes apart from our migration are required before we go public.

- Replace `eachDecl` to `walkDecls` to support new versions of PostCSS because right now it only works on PostCSS v4.x
- Update plugin's rule matching to match not only `background-image` but `background` shorthand as well
- Fix alpha in colors parsing

I have made all the required fixes locally, just need to clean up a little and push them into the repo.
After that I can make the tweet.

Here are the compiled examples by the way, all generated using our plugin: https://codepen.io/alx-khovansky/pen/NeGjPZ?editors=1100

@ai How would you like to show the examples in the tweet? Codepen link like the one above with the pre-generated polyfills or something else?

**Comment by ai** [comment]
@khovansky-al you need an image (tweets with images are more effective). I think CSS example of conic gradient, `postcssrc.js` example and how it looks in browser.

**Pull request merged**
